Updated readme - still more work to do but wanted to see what it looks like for now
AutonoLab/pteranodon pull request #79
Opened 2022-10-12 20:54 UTC by manassaini

2022-10-26 23:44 UTC, manassaini commented
Unable to add the package "uvloop" in PyCharm. There is no support for uvloop in Windows. This causing errors within Sphinx and not generating the documentation files correctly.

2022-10-28 20:38 UTC, justincdavis requested changes
Missing generated .rst files for actual implementations?

Refer to comments on README.md about requested changesd

2022-10-28 20:38 UTC, justincdavis commented on README.md
> +Information TBD
Contributing should be its own .md file CONTRIBUTING.md

2022-10-28 20:38 UTC, justincdavis commented on README.md
> +## Description
Remove same description that sits higher up

2022-10-28 20:38 UTC, justincdavis commented on README.md
> +
Add steps for our docker container (this is waiting on the docker from @david-shearon )

2022-10-29 20:40 UTC, manassaini commented
> Missing generated .rst files for actual implementations?
> 
> Refer to comments on README.md about requested changesd

2022-10-29 20:40 UTC, closed without merging

2022-10-29 20:41 UTC, manassaini commented
> 

I believe those are not needed. Only for directories. It is generating correct .html files for plugins and everything so should be fine