Auto Documentation & README
AutonoLab/pteranodon pull request #91
Opened 2022-10-30 18:57 UTC by manassaini

Pull request for auto documentation using Sphinx tool and README file

2022-10-31 14:42 UTC, justincdavis requested changes
Did you look into having readthedocs host everything for us? 

Please fill out the CONTRIBUTING.md

2022-10-31 20:25 UTC, manassaini commented on README.md
> +A framework to built on top of MAVSDK which provides physical/virtual drone abstraction, abstraction for all async calls,
I am confused on what you are asking. readthedocs already does host everything for us. All the docs are only on that site

2022-11-01 19:33 UTC, justincdavis commented
@david-shearon Waiting on your commit for Docker instructions to primary README, this could be pending updating the to .devcontainer format as well though

2022-11-03 05:28 UTC, justincdavis approved these changes

2022-11-03 05:28 UTC, merged