Docker
AutonoLab/pteranodon pull request #92
Opened 2022-10-31 14:42 UTC by david-shearon

2022-10-31 16:08 UTC, justincdavis reviewed
Probably change the outer most folder name to "containers", see note about the newline and question on the README running instructions.

2022-10-31 16:09 UTC, justincdavis commented
@carlsondev @david-shearon Should the workflows be updated to use this docker container now? Is that possible to do without publishing to the Docker container hub thing?

2022-10-31 16:36 UTC, david-shearon commented
Yes, it is possible. Maybe look here for reference: https://github.com/JonasVautherin/px4-gazebo-headless/tree/master/.github/workflows

2022-10-31 16:40 UTC, carlsondev commented
I was referring to the integration tests workflow, which requires having a MAV SDK server instance running alongside it, not the building and deploying of the docker container. This requires starting up the docker container as a service and establishing a network. It shouldn't be that difficult, but in practice, I haven't had any luck. 

@justincdavis All the other containers don't need it because they don't need all the extra PX4 stuff and they just need a base ubuntu.

2022-11-01 19:32 UTC, justincdavis commented
@david-shearon Can we actually update this container to use the .devcontainer framework that Github supports?

@carlsondev This could fix some of your issues as well.

https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers

2022-11-01 21:42 UTC, david-shearon commented
@justincdavis I'll look into it. Does that just entail changing the name of the directory?

2022-11-01 21:50 UTC, justincdavis commented
@david-shearon That and adding a docker.json or similar file (see the link). No changes to the Dockerfile are required

2022-11-02 18:35 UTC, justincdavis commented
@david-shearon @carlsondev I think this blogpost thing could be quite useful :)

https://bradyjoslin.com/blog/dev-action-container

2022-11-03 16:17 UTC, david-shearon commented
@justincdavis, @carlsondev  helped me with the dev container. Is this what you were looking for? It doesn't build the docker container for some reason.

2022-11-03 18:19 UTC, justincdavis requested changes
As far as I can tell this looks like exactly what we want. I am confused why it would not be building since you essentially should have just renamed the folder to .devcontainer and added that .json file?

If you can send me the errors LMK and also not the ubuntu 20.04 change, that is what I have been using I never realized the Docker used that,

2022-11-03 18:19 UTC, justincdavis commented on .devcontainer/Dockerfile
> +FROM ubuntu:18.04
We should really change this to ubuntu:20.04 I guess I missed this before

```suggestion
FROM ubuntu:20.04
```

2022-11-03 18:19 UTC, justincdavis commented on .devcontainer/devcontainer.json
> +}
```suggestion
}

```

2022-11-04 03:50 UTC, justincdavis approved these changes

2022-11-04 05:09 UTC, merged